my_app_filmotheque:
    resource: "@myAppFilmothequeBundle/Controller/"
    type:     annotation
    prefix:   /myapp
    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
    
myapp_acteur_lister:
  path:     /acteur/lister
  defaults: { _controller: myAppFilmothequeBundle:Acteur:lister }
myapp_acteur_ajouter:
  path:     /acteur/ajouter
  defaults: { _controller: myAppFilmothequeBundle:Acteur:ajouter }
myapp_acteur_modifier:
  path:     /acteur/modifier/{id}
  defaults: { _controller: myAppFilmothequeBundle:Acteur:modifier }
myapp_acteur_supprimer:
  path:     /acteur/supprimer/{id}
  defaults: { _controller: myAppFilmothequeBundle:Acteur:supprimer }

