cours_sport:
    path:     /
    defaults: { _controller: MaudSportBundle:Save:index }
  
cours_sport_favorite:
    path:    /favorite
    defaults:
        _controller: MaudSportBundle:Save:favorite
        
cours_sport_bookCourse:
    path:    /nextsave/{password}/{id}/{targetClubName}/{targetCourseName}/{targetDay}
    defaults:
        _controller: MaudSportBundle:Save:bookCourse
    requirements:
        password: .+
        id : \d+
        
cours_sport_addFavorite:
    path:    /addFavorite
    defaults:
        _controller: MaudSportBundle:Save:addFavorite
        
cours_sport_delete:
    path:    /delete/{id}/{password}
    defaults:
        _controller: MaudSportBundle:Save:delete
    requirements:
        id: \d+
        password : .+
        
cours_sport_cancelBooking:
    path:    /cancel/{id}/{password}
    defaults:
        _controller: MaudSportBundle:Save:cancelBooking
    requirements:
        id: \d+
        password : .+