cours_sport:
    path:     /
    defaults: { _controller: MaudSportBundle:Save:index }
  
cours_sport_reserver:
    path:    /reserver
    defaults:
        _controller: MaudSportBundle:Save:reserver
        
cours_sport_nextsave:
    path:    /nextsave/{password}/{id}/{targetClubName}/{targetCourseName}/{targetDay}
    defaults:
        _controller: MaudSportBundle:Save:nextsave
    requirements:
        password: .+
        id : \d+

cours_sport_view:
    path:    /reserver/{id}
    defaults:
        _controller: MaudSportBundle:Save:view
    requirements:
        id: \d+
        
        
cours_sport_add:
    path:    /add
    defaults:
        _controller: MaudSportBundle:Save:add
        
cours_sport_delete:
    path:    /delete/{id}/{password}
    defaults:
        _controller: MaudSportBundle:Save:delete
    requirements:
        id: \d+
        password : .+
        
cours_sport_cancel:
    path:    /cancel/{id}/{password}
    defaults:
        _controller: MaudSportBundle:Save:delete
    requirements:
        id: \d+
        password : .+